version: '3'
services:
  mysql_db:
    image: mysql:latest
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: spark_networks_test
      MYSQL_USER: ti
      MYSQL_PASSWORD: secret
    ports:
      - 3307:3306
    networks:
      - app-tier
  
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    links:
      - mysql_db
    networks:
      - app-tier
    restart: always
    entrypoint:
      "python /app/main.py"
      

networks:
  app-tier:
    driver: bridge
